title: "MethodologyPedia"
description: "The Encyclopedia of Software Development Methodologies"
url: "https://methodologypedia.com"
baseurl: ""

permalink: pretty

collections:
  methodologies:
    output: true
    permalink: /methodologies/:slug/

plugins:
  - jekyll-polyglot
  - jekyll-sitemap

languages: ["en", "en-gb", "ar", "es"]
default_lang: "en"
exclude_from_localizations: ["assets", "favicon.ico", "robots.txt", "sitemap.xml"]

sass:
  sass_dir: assets/css
  style: compressed

kramdown:
  input: GFM

meta:
  author: "Radical Dave"
  github: "https://github.com/radical-dave/methodologypedia"

web3forms_key: ""
dispatch_token: ""
